---
dist: trusty
sudo: required
language: generic

services:
  - docker

env:
  global:
    - GO_IMAGE=golang:1.9
  matrix:
    - MYSQL_IMAGE=mysql/mysql-server:5.5
    - MYSQL_IMAGE=mysql/mysql-server:5.6
    - MYSQL_IMAGE=mysql/mysql-server:5.7
    - MYSQL_IMAGE=mysql/mysql-server:8.0

before_install:
  - sudo service mysql stop
  - curl -L https://github.com/drone/drone-cli/releases/download/v0.7.0/drone_linux_amd64.tar.gz | tar -zx -C /tmp
  - sudo install -t /usr/local/bin /tmp/drone

  - docker --version
  - drone --version

script:
  - make
